# Generated by Django 5.1.15 on 2026-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('wishlist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
