# Generated by ChatGPT on 2026-03-26

from django.db import migrations, models


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')

    year_counters = {}
    orders = Order.objects.filter(order_number__isnull=True).order_by('created_at', 'id')
    for order in orders:
        year = order.created_at.year if order.created_at else 1970
        year_counters.setdefault(year, 0)
        year_counters[year] += 1
        order.order_number = f"ord00{year}{year_counters[year]:04d}"
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=13, null=True, unique=True),
        ),
        migrations.RunPython(populate_order_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=13, unique=True),
        ),
    ]
